server:
  connection-timeout: 5000
  port: 8090
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: DEBUG
    freemarker: INFO
    org.springframework.ui.freemarker: INFO
  pattern:
    console: "%highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    

planets:
  service:
    url: http://localhost:8091/planets

spring:
  freemarker.cache: false

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bzhcamp
            user-name-attribute: preferred_username

        registration:
          keycloak:
            client-id: app-springboot
            client-secret: I8fP9ghnym3mIxI5fcHgKaGYnRTsHd60
            authorization-grant-type: authorization_code
            
            scope: 
              - openid

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bzhcamp

